### ISSUE TITLE
List 상행선 하행선 오류

### ISSUE THREAD

**Issue by land-waters** [tukcom2022SP/i3#2]
상행선 하행선 나눠져있지만 리스트에는 상행으로만 표기

**Comment by jisssuu** [comment]
List ID 구분에서 stationName이 같은 데이터가 있어 오류가 발생.
따라서 모든 Data가 구분되는 변수로 ID  재설정
( 모든 Data가 구분되는 변수가 StationCount 이지만 Int 형이여서 String으로 변경 )

**Comment by land-waters** [comment]
List ID 구분에서 stationName이 같은 데이터가 있어 오류가 발생.
따라서 모든 Data가 구분되는 변수로 ID 재설정
( 모든 Data가 구분되는 변수가 StationCount 이지만 Int 형이여서 String으로 변경 )
